version = 0.1
[default.deploy.parameters]
stack_name = "fetch-from-s3-3"
resolve_s3 = true
s3_prefix = "fetch-from-s3-3"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
